---
- name: play 1
  hosts: {{ hostsName }}
  gather_facts: false
  tasks: 
    - name: task1 in play1
      shell: |
        yum -y install ntpdate && ntpdate -u  pool.ntp.org && date
      debug: 
        msg: "output task1 in play1"

