---
- name: play 1
  hosts: "{{ hostsName }}"
  gather_facts: false
  tasks: 
    - name: task1 in play1
      shell: |
        ntpdate -u  pool.ntp.org && date
    
    - name: task2 in play1
      debug: 
        msg: "output task1 in play1"
