---
# ansible-playbook dateup.yaml --extra-vars "{'hostsName': ['192.168.0.243','192.168.0.25']}" --verbose
# ansible-playbook dateup.yaml --extra-vars "hostsName=192.168.60.135" --verbose
- name: dateup
  hosts: "{{ hostsName }}"
  gather_facts: true
  tasks: 
    - name: info in ansible_facts
      debug: 
        var: ansible_facts

    - name: update date centos7
      shell: |
        ntpdate -u  pool.ntp.org && date
      when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "7"

    - name: Check chronyd service status
      shell: |
        ps -ef | grep chronyd
      register: chronyd_process
      ignore_errors: true

    - name: Debug chronyd process status
      debug:
        msg: >
          chronyd process is {{ 'running' if chronyd_process.stdout != '' else 'not running' }}

    - name: update date centos8
      shell: |
        yum install -y chrony
        systemctl status chronyd
      when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "8"

    - name: msg output
      debug: 
        msg: "output task1 in play1"
