---
# ansible-playbook docker_install.yaml --extra-vars "{'hostsName': ['192.168.0.25']}" --verbose
# ansible-playbook docker_install.yaml --extra-vars "hostsName=192.168.0.25" --verbose
- name: docker_install
  hosts: "{{ hostsName }}"
  gather_facts: true
  tasks:
    - name: msg
      debug:
        msg: "output msg {{ ansible_host }}"

    - name: create mysql log dir
      shell: |
        mkdir -p /mydata/mysql/log
        mkdir -p /mydata/mysql/data
        mkdir -p /mydata/mysql/conf

    - name: docker pull 5.7
      shell: |
        docker pull mysql:5.7

    - name: my.cnf edit
      shell: |
        echo '
        [client]
        default-character-set=utf8mb4
  
        [mysql]
        default-character-set=utf8mb4
  
        [mysqld]
        init_connect="SET collation_connection = utf8mb4_unicode_ci"
        init_connect="SET NAMES utf8mb4"
        character-set-server=utf8mb4
        collation-server=utf8mb4_unicode_ci
        skip-character-set-client-handshake
        skip-name-resolve
        ' > /mydata/mysql/conf/my.cnf

    - name: docker run mysql:5.7
      shell: |
        docker run -d -p 3306:3306 --name mysql \
        -v /mydata/mysql/log:/var/log/mysql \
        -v /mydata/mysql/data:/var/lib/mysql \
        -v /mydata/mysql/conf/my.cnf:/etc/my.cnf \
        --restart=always \
        -e MYSQL_ROOT_PASSWORD=123456 \
        -d mysql:5.7