---
# ansible-playbook docker_install.yaml --extra-vars "{'hostsName': [‘192.168.0.25’]}" --verbose
# ansible-playbook docker_install.yaml --extra-vars "hostsName=192.168.0.25" --verbose
- name: server_init
  hosts: "{{ hostsName }}"
  gather_facts: true
  tasks:
    - name: msg
      debug:
        msg: "output msg {{ ansible_host }}"

    - name: docker install
      shell: |
        yum install -y yum-utils \
          device-mapper-persistent-data \
          lvm2
        yum-config-manager \
          --add-repo \
          https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
        yum -y install docker-ce docker-ce-cli containerd.io

    - name: docker start
      shell: |
        yum list docker-ce --showduplicates | sort -r
        sudo systemctl start docker

    - name: enable docker
      shell: |
        systemctl enable docker.service
