---
- name: play 1
  hosts: "{{ hostsName }}"
  gather_facts: true
  tasks: 
    - name: info in ansible_facts
      debug: 
        var: ansible_facts

    - name: task1 in play1
      shell: |
        echo "ok"
    
    - name: task2 in play1
      debug: 
        msg: "output task1 in play1"
