---
- name: node exporter
  hosts: "{{ hosts }}"
  gather_facts: false
  tasks:
    - name: msg
      debug:
        msg: "output msg {{ ansible_host }}"

    - name: kill node_exporter
      shell: |
        ps -ef |grep node_exporter |awk '{print $2}' |xargs kill
      ignore_errors: true

    - name: start node_exporter
      shell: |
        cd /opt/node_exporter-1.9.0.linux-amd64 && nohup ./node_exporter --web.listen-address=:39100 >/dev/null 2>&1 &

    - name: check node_exporter
      shell: |
        ps -ef|grep node_exporter

    - name: kill prometheus
      shell: |
        ps -ef |grep prometheus |awk '{print $2}' |xargs kill
      ignore_errors: true

    - name: start prometheus
      shell: |
        cd /opt/prometheus-2.53.4.linux-amd64 && nohup ./prometheus >/dev/null 2>&1 &
      when: ansible_host == '192.168.60.134'

    - name: check prometheus
      shell: |
        ps -ef|grep prometheus

    - name: kill grafana
      shell: |
        ps -ef |grep grafana |awk '{print $2}' |xargs kill
      ignore_errors: true

    - name: start grafana
      shell: |
        cd /opt/grafana-v11.5.2/bin && nohup ./grafana server >/dev/null 2>&1 &
      when: ansible_host == '192.168.60.134'

    - name: check grafana
      shell: |
        ps -ef|grep grafana