---
- name: node exporter
  hosts: "{{ hosts }}"
  gather_facts: false
  tasks:
    - name: msg
      debug:
        msg: "output msg {{ ansible_host }}"

    - name: start node_exporter
      shell: |
        cd /opt/node_exporter-1.9.0.linux-amd64 && nohup ./node_exporter --web.listen-address=:39100 >/dev/null 2>&1 &

    - name: check node_exporter
      shell: |
        ps -ef|grep node_exporter