---
- name: play 1
  hosts: "{{ hostsName }}"
  gather_facts: false
  tasks:
    - name: info in ansible_facts
      debug:
        var: ansible_facts

    - name: yum update
      shell: |
        yum makecache
        yum install -y epel-release
        yum install -y chrony

    - name: task2 in play1
      debug:
        msg: "output task1 in play1"
